### ISSUE TITLE
Train custom graph embeddings

### ISSUE THREAD

**Issue by malteos** [viswavi/CitationIE#3]
Hi there,

thanks for your interesting paper! I'd like to apply your approach on another dataset so I cannot reuse your pretrained graph embedding. Can you provide the code as well to train new graph embeddings?

Cheers
Malte

**Comment by viswavi** [comment]
Hi Malte, thanks for your interest! Our graph embeddings are generated using https://github.com/DeepGraphLearning/graphvite, which is an awesome, easy-to-use graph embedding generation package.

However, I realized that we never checked in the code to generate a citation graph in the format expected by GraphVite. I'll find this code, add it into the repo, get back to you in a day or two

**Comment by viswavi** [comment]
Actually, I realized the code here is in the repo:
https://github.com/viswavi/CitationIE/blob/main/join_scirex_and_s2orc.py#L665. You just need to uncomment lines 660 through 665.

This code also contains everything you'll need to construct a citation graph around the papers in your custom dataset. You can replace `all_scirex_docids = get_scirex_docids()` [in line 639](https://github.com/viswavi/CitationIE/blob/bd163fd131ae327443310fb89058457b7a47ecab/join_scirex_and_s2orc.py#L639) with a different set of SemanticScholar paper ID's, which will function as the set of base papers around which the citation graph is constructed.

This citation graph construction process takes several hours to run and requires a fair amount of bandwidth, so if your custom dataset consists of papers in the AI/ML domain, let me know and I can send you a pre-constructed citation graph that you can use.

After running this script, it will generate a graphvite input training data file that you can plug into the graphvite model config ([e.g. here](https://github.com/DeepGraphLearning/graphvite/blob/master/config/graph/deepwalk_flickr.yaml#L10))

**Comment by malteos** [comment]
Thanks for the reply @viswavi. What config / DeepWalk hyperparameters did you use?

**Comment by viswavi** [comment]
This is the exact config we used in our paper results:
[graph.yaml.txt](https://github.com/viswavi/CitationIE/files/7899880/graph.yaml.txt)
